// ============================================================================
// RadShield - Editor Module (Phase 1)
// The scene is a persistent document (SceneModel). This module owns:
//   - the document + undo/redo (snapshot based)
//   - selection, viewport interaction callbacks (via Scene.initEditorControls)
//   - the outliner, properties panel, context menu, mode toolbar, keyboard
//   - insert / duplicate / delete / save / load / new / tank-template merge
// index.html supplies { refresh, setStatus } hooks and the calculation flow.
// ============================================================================

const Editor = (() => {

    const IN = 2.54;               // cm per inch (matches Geometry.INCH_TO_CM)
    const MAX_UNDO = 50;

    let model = null;              // SceneModel document
    let hooks = {};                // { refresh(frame), setStatus(msg), onDosePick(pt) }
    let selection = null;          // volume id or null
    let undoStack = [];
    let redoStack = [];
    let ctxMenuEl = null;
    let insertCounter = 0;

    // IDs generated by the tank template (replaced on template rebuild)
    const TANK_ID_RE = /^(source-liquid|source-sludge|clean-water|wall-\d+|floor-\d+|lid|plug)$/;

    // -----------------------------------------------------------------------
    // Init
    // -----------------------------------------------------------------------
    function init(initialModel, hooksArg) {
        model = initialModel;
        hooks = hooksArg || {};

        Scene.initEditorControls({
            onSelect: (id, screen) => handleViewportPick(id, screen),
            onPickPoint: (pt) => placeDosePoint(pt),
            onMeasure: (a, b) => reportMeasure(a, b),
            onContextMenu: (id, screen, pt) => showContextMenu(id, screen, pt),
            onTransformStart: () => pushUndo(),
            onTransformEnd: (id, posCm, rotDeg) => {
                const vol = model.getVolume(id);
                if (!vol) return;
                vol.position = { x: posCm.x, y: posCm.y, z: posCm.z };
                vol.setRotation(rotDeg);
                renderProperties();
                status('Moved ' + displayName(vol));
            }
        });

        bindModeToolbar();
        bindKeyboard();
        document.addEventListener('pointerdown', (e) => {
            if (ctxMenuEl && !ctxMenuEl.contains(e.target)) hideContextMenu();
        });

        renderOutliner();
        renderProperties();
        updateHelp();
    }

    function status(msg) { if (hooks.setStatus) hooks.setStatus(msg); }

    // Full refresh: 3D scene + panels, selection preserved
    function refreshAll(frame) {
        if (hooks.refresh) hooks.refresh(!!frame);
        Scene.setSelected(selection);
        renderOutliner();
        renderProperties();
    }

    // -----------------------------------------------------------------------
    // Undo / redo (whole-scene snapshots)
    // -----------------------------------------------------------------------
    function snapshot() {
        return JSON.stringify({ scene: model.toJSON(), selection: selection });
    }

    function restore(snap) {
        const data = JSON.parse(snap);
        model = Geometry.sceneFromJSON(data.scene);
        selection = data.selection && model.getVolume(data.selection) ? data.selection : null;
        refreshAll(false);
    }

    function pushUndo() {
        undoStack.push(snapshot());
        if (undoStack.length > MAX_UNDO) undoStack.shift();
        redoStack = [];
    }

    function undo() {
        if (!undoStack.length) { status('Nothing to undo'); return; }
        redoStack.push(snapshot());
        restore(undoStack.pop());
        status('Undo');
    }

    function redo() {
        if (!redoStack.length) { status('Nothing to redo'); return; }
        undoStack.push(snapshot());
        restore(redoStack.pop());
        status('Redo');
    }

    // -----------------------------------------------------------------------
    // Selection
    // -----------------------------------------------------------------------
    // Every pick (viewport click or outliner click) routes through here so
    // an in-progress relationship (mate) can capture it.
    function handleViewportPick(id, screen) {
        if (mateState) { handleMateClick(id); return; }
        select(id);
        if (Scene.getMode() === 'dimension') {
            if (id && screen) showDimEditor(id, screen);
            else if (!id) hideDimEditor();
        }
    }

    function reportMeasure(a, b) {
        if (!b) {
            status('Measure: point 1 set at (' + fmtPt(a) + ') — click the second point');
            return;
        }
        const dx = b.x - a.x, dy = b.y - a.y, dz = b.z - a.z;
        const dist = Math.sqrt(dx * dx + dy * dy + dz * dz);
        status('Distance: ' + (dist / IN).toFixed(2) + '" (' + (dist / 30.48).toFixed(2) +
            ' ft) from (' + fmtPt(a) + ') to (' + fmtPt(b) + ') — click to start a new measurement');
    }

    function fmtPt(p) {
        return (p.x / IN).toFixed(1) + '", ' + (p.y / IN).toFixed(1) + '", ' +
               (p.z / IN).toFixed(1) + '"';
    }

    function select(id) {
        selection = id;
        Scene.setSelected(id);
        renderOutliner();
        renderProperties();
        if (id) {
            const vol = model.getVolume(id);
            status('Selected: ' + displayName(vol));
        }
    }

    function displayName(vol) {
        if (!vol) return '?';
        return vol.label || (vol.constructor.name.replace('Volume', '') + ' ' + vol.id);
    }

    // -----------------------------------------------------------------------
    // Document operations
    // -----------------------------------------------------------------------
    function addVolume(kind, role, atPt) {
        pushUndo();
        insertCounter++;
        const pt = atPt || { x: 0, y: 0, z: 0 };
        const base = {
            role: role,
            materialKey: role === 'source' ? 'water' : 'steel',
            position: { x: pt.x, y: Math.max(pt.y, 0), z: pt.z },
            priority: role === 'source' ? 25 : 60,
            label: (role === 'source' ? 'Source ' : 'Shield ') + insertCounter
        };
        if (role === 'source') {
            base.isotopeKey = 'Co-60';
            base.activity_Ci = 1;
        }

        let vol;
        if (kind === 'annulus') {
            vol = new Geometry.AnnulusVolume({
                ...base,
                dimensions: { innerRadius: 6 * IN, outerRadius: 7 * IN, height: 12 * IN }
            });
        } else if (kind === 'disk') {
            vol = new Geometry.DiskVolume({
                ...base,
                dimensions: { radius: 6 * IN, thickness: 1 * IN }
            });
        } else if (kind === 'box') {
            vol = new Geometry.BoxVolume({
                ...base,
                dimensions: { width: 12 * IN, depth: 12 * IN, height: 12 * IN }
            });
        } else if (kind === 'plate') {
            // A "plane" / wall: thin box, easy to rotate into any orientation
            vol = new Geometry.BoxVolume({
                ...base,
                label: (role === 'source' ? 'Source ' : 'Plate ') + insertCounter,
                dimensions: { width: 24 * IN, depth: 24 * IN, height: 0.5 * IN }
            });
        } else if (kind === 'sphere') {
            vol = new Geometry.SphereVolume({
                ...base,
                dimensions: { radius: 6 * IN }
            });
        } else {
            vol = new Geometry.CylinderVolume({
                ...base,
                dimensions: { radius: 6 * IN, height: 12 * IN }
            });
        }
        model.addVolume(vol);
        refreshAll(false);
        select(vol.id);
        status('Added ' + displayName(vol) +
            ' — size it in the Selected Object panel, or press S and click it (Smart Dimension)');
    }

    function deleteVolume(id) {
        const vol = model.getVolume(id);
        if (!vol) return;
        pushUndo();
        model.removeVolume(id);
        if (selection === id) selection = null;
        refreshAll(false);
        status('Deleted ' + displayName(vol));
    }

    function duplicateVolume(id) {
        const vol = model.getVolume(id);
        if (!vol) return;
        pushUndo();
        const j = vol.toJSON();
        delete j.id;                        // new unique id
        j.position.x += 6 * IN;             // offset 6" in X
        j.label = (j.label || 'Volume') + ' copy';
        const copy = Geometry.volumeFromJSON(j);
        model.addVolume(copy);
        refreshAll(false);
        select(copy.id);
        status('Duplicated');
    }

    function setMaterial(id, key) {
        const vol = model.getVolume(id);
        if (!vol || vol.materialKey === key) return;
        pushUndo();
        vol.materialKey = key;
        refreshAll(false);
    }

    function setRole(id, role) {
        const vol = model.getVolume(id);
        if (!vol || vol.role === role) return;
        pushUndo();
        vol.role = role;
        if (role === 'source') {
            vol.isotopeKey = vol.isotopeKey || 'Co-60';
            vol.activity_Ci = vol.activity_Ci || 1;
        }
        refreshAll(false);
    }

    function toggleVisible(id) {
        const vol = model.getVolume(id);
        if (!vol) return;
        pushUndo();
        vol.visible = !vol.visible;
        refreshAll(false);
    }

    // Include/exclude a volume from the dose calculation (independent of
    // visibility). Excluded volumes draw ghosted and contribute nothing.
    function toggleEnabled(id) {
        const vol = model.getVolume(id);
        if (!vol) return;
        pushUndo();
        vol.enabled = vol.enabled === false;
        refreshAll(false);
        status(displayName(vol) + (vol.enabled
            ? ' included in calculation'
            : ' EXCLUDED from calculation (ghosted)'));
    }

    // -----------------------------------------------------------------------
    // Align operations (one-shot "mates"): move the selected volume into a
    // fixed relationship with a target volume. All modes make the axes
    // parallel (rotation copied from target), then place the mover's
    // bottom-center in the target's local frame.
    // -----------------------------------------------------------------------
    const ALIGN_MODES = [
        { key: 'concentric', label: 'Concentric (share axis)' },
        { key: 'ontop',      label: 'Place on top (flush faces)' },
        { key: 'under',      label: 'Place underneath (flush faces)' },
        { key: 'flush',      label: 'Coplanar bottom faces' },
        { key: 'center',     label: 'Center inside target' },
        { key: 'rot',        label: 'Match rotation only' }
    ];

    function volHeight(v) {
        if (v._type && v._type() === 'sphere') return v.radius * 2;
        return v.height || v.thickness || 0;
    }

    function alignVolumes(moverId, targetId, mode) {
        const mover = model.getVolume(moverId);
        const target = model.getVolume(targetId);
        if (!mover || !target || moverId === targetId) return;
        pushUndo();

        // Mover's bottom-center expressed in the target's local frame
        const q = target.worldToLocal(mover.position.x, mover.position.y, mover.position.z);
        let nq = null;
        switch (mode) {
            case 'concentric': nq = { x: 0, y: q.y, z: 0 }; break;
            case 'ontop':      nq = { x: 0, y: volHeight(target), z: 0 }; break;
            case 'under':      nq = { x: 0, y: -volHeight(mover), z: 0 }; break;
            case 'flush':      nq = { x: q.x, y: 0, z: q.z }; break;
            case 'center':     nq = { x: 0, y: (volHeight(target) - volHeight(mover)) / 2, z: 0 }; break;
            case 'rot':        nq = null; break;
            default: return;
        }

        mover.setRotation({ ...target.rotation });
        if (nq) mover.position = target.localToWorld(nq.x, nq.y, nq.z);

        refreshAll(false);
        select(moverId);
        const label = (ALIGN_MODES.find(m => m.key === mode) || {}).label || mode;
        status(label + ': ' + displayName(mover) + ' → ' + displayName(target));
    }

    // -----------------------------------------------------------------------
    // Relationship workflow (SolidEdge-style toolbar mates)
    // Click a relationship button, then click the object to move, then the
    // target. If something is already selected it becomes the mover and only
    // the target click is needed. Esc cancels.
    // -----------------------------------------------------------------------
    let mateState = null;   // { mode, moverId } | null

    function mateLabel(key) {
        return (ALIGN_MODES.find(m => m.key === key) || { label: key }).label;
    }

    function startMate(modeKey) {
        if (mateState && mateState.mode === modeKey) {   // toggle off
            cancelMate('Relationship cancelled');
            return;
        }
        const mover = selection ? model.getVolume(selection) : null;
        mateState = { mode: modeKey, moverId: mover ? selection : null };
        updateMateButtons();
        setMode('select');
        status(mover
            ? mateLabel(modeKey) + ': moving "' + displayName(mover) + '" — click the TARGET object'
            : mateLabel(modeKey) + ': click the object to MOVE');
        updateHelp();
    }

    function cancelMate(msg) {
        mateState = null;
        updateMateButtons();
        if (msg) status(msg);
        updateHelp();
    }

    function handleMateClick(id) {
        if (!id) { cancelMate('Relationship cancelled (clicked empty space)'); return; }
        if (!mateState.moverId) {
            mateState.moverId = id;
            select(id);
            status(mateLabel(mateState.mode) + ': moving "' +
                displayName(model.getVolume(id)) + '" — now click the TARGET object');
            updateHelp();
            return;
        }
        if (id === mateState.moverId) {
            status('Target must be a different object — click another object, or Esc to cancel');
            return;
        }
        const st = mateState;
        mateState = null;
        updateMateButtons();
        alignVolumes(st.moverId, id, st.mode);
        updateHelp();
    }

    function updateMateButtons() {
        document.querySelectorAll('[data-mate]').forEach(btn => {
            btn.classList.toggle('active',
                !!mateState && btn.dataset.mate === mateState.mode);
        });
    }

    // Replace tank-template volumes, keep everything the user added
    function applyTankTemplate(tankModel) {
        pushUndo();
        model.volumes = model.volumes.filter(v => !TANK_ID_RE.test(v.id));
        for (const v of tankModel.volumes) model.addVolume(v);
        if (selection && !model.getVolume(selection)) selection = null;
        refreshAll(true);
        status('Tank template rebuilt');
    }

    function newScene() {
        if (model.volumes.length &&
            !confirm('Clear the entire scene? (This is undoable with Ctrl+Z)')) return;
        pushUndo();
        model.volumes = [];
        selection = null;
        refreshAll(false);
        status('New empty scene');
    }

    // -----------------------------------------------------------------------
    // Save / load
    // -----------------------------------------------------------------------
    function saveToFile(extras) {
        const data = model.toJSON();
        Object.assign(data, extras || {});
        const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
        const a = document.createElement('a');
        a.href = URL.createObjectURL(blob);
        a.download = 'radshield-scene.json';
        a.click();
        URL.revokeObjectURL(a.href);
        status('Scene saved (' + model.volumes.length + ' volumes)');
    }

    function loadFromFile(file, onExtras) {
        const reader = new FileReader();
        reader.onload = () => {
            try {
                const data = JSON.parse(reader.result);
                const loaded = Geometry.sceneFromJSON(data);
                pushUndo();
                model = loaded;
                selection = null;
                if (onExtras) onExtras(data);
                refreshAll(true);
                status('Loaded ' + file.name + ' (' + model.volumes.length + ' volumes)');
            } catch (e) {
                status('Load failed: ' + e.message);
            }
        };
        reader.readAsText(file);
    }

    // -----------------------------------------------------------------------
    // Dose point placement (viewport pick) — the app owns the dose point
    // list; it is handed the picked location via the onDosePick hook.
    // -----------------------------------------------------------------------
    function placeDosePoint(pt) {
        if (hooks.onDosePick) hooks.onDosePick(pt);
        setMode('select');
        status('Dose point placed at (' + (pt.x / IN).toFixed(1) + '", ' +
            (pt.y / IN).toFixed(1) + '", ' + (pt.z / IN).toFixed(1) + '")');
    }

    // -----------------------------------------------------------------------
    // Interaction mode + toolbar
    // -----------------------------------------------------------------------
    const MODES = ['select', 'translate', 'rotate', 'dose', 'measure', 'dimension'];

    function setMode(mode) {
        Scene.setMode(mode);
        if (mode !== 'dimension') hideDimEditor();
        for (const m of MODES) {
            const btn = document.getElementById('mode-' + m);
            if (btn) btn.classList.toggle('active', m === mode);
        }
        const tips = {
            select: 'Select mode: click a volume',
            translate: 'Move mode: drag the arrows (snap 0.25")',
            rotate: 'Rotate mode: drag the rings (snap 15°)',
            dose: 'Click anywhere to place the dose point',
            measure: 'Measure: click the first point (on any object or the floor)',
            dimension: 'Smart Dimension: click an object to edit its dimensions in place'
        };
        status(tips[mode] || '');
        updateHelp();
    }

    // -----------------------------------------------------------------------
    // Contextual "How to" bar (bottom of the viewport): always explains the
    // active tool; during a relationship it walks through the steps.
    // -----------------------------------------------------------------------
    const MODE_HELP = {
        select: ['Select (V)',
            'Click an object to select it, then edit it in the Selected Object panel on the left. ' +
            'Left-drag orbits the camera, right-drag pans, scroll zooms. ' +
            'Right-click an object for actions (duplicate, material, align…); right-click empty space to add a shape there. ' +
            'Del = delete, Ctrl+D = duplicate, Ctrl+Z = undo.'],
        translate: ['Move (G)',
            'Drag the red/green/blue arrows to move the selected object (¼" snap; green = up). ' +
            'Click a different object to move that one instead. ' +
            'For exact coordinates use the X/Y/Z fields in the Selected Object panel. Esc = back to Select.'],
        rotate: ['Rotate (R)',
            'Drag the colored rings to rotate the selected object (15° snap). ' +
            'For exact angles use the Rot X/Y/Z fields in the Selected Object panel. Esc = back to Select.'],
        dose: ['Dose Point (D)',
            'Click any object surface or the floor to drop the dose point there, then press "Calculate Dose Rate". ' +
            'You can also type coordinates in the Dose Point panel on the left.'],
        measure: ['Measure (M)',
            'Click a first point, then a second (on object surfaces or the floor). ' +
            'A label shows the straight-line distance plus the X/Y/Z offsets between the two points. ' +
            'Click again to start a new measurement. Esc = exit.'],
        dimension: ['Smart Dimension (S)',
            'Click any object — a popup appears at your cursor with its dimensions (radius, height, width…). ' +
            'Type new values and they apply instantly (undoable with Ctrl+Z). ' +
            'Click another object to edit that one next. Esc = close.']
    };

    const MATE_DESC = {
        concentric: 'Concentric moves it onto the target’s axis (keeps its position along the axis).',
        ontop: 'On Top sets its bottom face flush on the target’s top face, centered on the axis.',
        under: 'Beneath sets it flush against the target’s bottom face, centered on the axis.',
        flush: 'Flush puts both bottom faces on the same plane (keeps the sideways offset).',
        center: 'Center In centers it inside the target.',
        rot: 'Parallel matches its orientation to the target without moving it.'
    };

    function updateHelp() {
        const el = document.getElementById('helpbar');
        if (!el) return;
        let title, text;
        if (mateState) {
            title = 'Relationship: ' + mateLabel(mateState.mode);
            text = (mateState.moverId
                ? 'Step 2 of 2 — click the TARGET object (in the 3D view or the Scene Objects list). '
                : 'Step 1 of 2 — click the object you want to MOVE. ')
                + (MATE_DESC[mateState.mode] || '') + '  Esc cancels.';
        } else {
            const h = MODE_HELP[Scene.getMode()] || ['', ''];
            title = h[0]; text = h[1];
        }
        el.innerHTML = '<span class="help-title">' + title + '</span><span class="help-text">' + text + '</span>';
    }

    function bindModeToolbar() {
        for (const m of MODES) {
            const btn = document.getElementById('mode-' + m);
            if (btn) btn.addEventListener('click', () => setMode(m));
        }
    }

    // -----------------------------------------------------------------------
    // Keyboard shortcuts
    // -----------------------------------------------------------------------
    function bindKeyboard() {
        document.addEventListener('keydown', (e) => {
            const tag = (e.target.tagName || '').toLowerCase();
            if (tag === 'input' || tag === 'textarea' || tag === 'select') return;

            if (e.ctrlKey && e.key.toLowerCase() === 'z' && !e.shiftKey) {
                e.preventDefault(); undo(); return;
            }
            if ((e.ctrlKey && e.key.toLowerCase() === 'y') ||
                (e.ctrlKey && e.shiftKey && e.key.toLowerCase() === 'z')) {
                e.preventDefault(); redo(); return;
            }
            if (e.ctrlKey && e.key.toLowerCase() === 'd') {
                e.preventDefault();
                if (selection) duplicateVolume(selection);
                return;
            }
            if (e.key === 'Delete' && selection) { deleteVolume(selection); return; }
            if (e.key === 'Escape') {
                hideContextMenu(); hidePipeBuilder(); hideDimEditor();
                if (mateState) { cancelMate('Relationship cancelled'); return; }
                select(null); setMode('select');
                return;
            }

            switch (e.key.toLowerCase()) {
                case 'v': setMode('select'); break;
                case 'g': setMode('translate'); break;
                case 'r': setMode('rotate'); break;
                case 'd': setMode('dose'); break;
                case 'm': setMode('measure'); break;
                case 's': setMode('dimension'); break;
            }
        });
    }

    // -----------------------------------------------------------------------
    // Outliner
    // -----------------------------------------------------------------------
    function materialColorHex(vol) {
        const c = vol.role === 'source'
            ? Scene.COLORS.source
            : (Scene.COLORS[vol.materialKey] || 0x888888);
        return '#' + c.toString(16).padStart(6, '0');
    }

    function renderOutliner() {
        const list = document.getElementById('outlinerList');
        if (!list) return;
        list.innerHTML = '';

        if (!model.volumes.length) {
            list.innerHTML = '<div class="outliner-empty">No objects. Build the tank template or right-click the viewport to add shapes.</div>';
            return;
        }

        for (const vol of model.volumes) {
            const row = document.createElement('div');
            row.className = 'outliner-item'
                + (vol.id === selection ? ' selected' : '')
                + (vol.enabled === false ? ' calc-off' : '');

            const dot = document.createElement('span');
            dot.className = 'outliner-dot';
            dot.style.background = materialColorHex(vol);

            const name = document.createElement('span');
            name.className = 'outliner-name';
            name.textContent = displayName(vol);
            name.title = vol.id + ' (priority ' + vol.priority + ')';

            const badge = document.createElement('span');
            badge.className = 'outliner-badge ' + vol.role;
            badge.textContent = vol.role === 'source' ? 'SRC'
                : (vol.role === 'container' ? 'TANK' : 'SHLD');

            const calc = document.createElement('input');
            calc.type = 'checkbox';
            calc.className = 'outliner-calc';
            calc.checked = vol.enabled !== false;
            calc.title = 'Include in dose calculation (unchecked = ghosted, ignored by physics)';
            calc.addEventListener('click', (e) => { e.stopPropagation(); toggleEnabled(vol.id); });

            const eye = document.createElement('button');
            eye.className = 'outliner-eye' + (vol.visible ? '' : ' off');
            eye.textContent = vol.visible ? '\u{1F441}' : '✖';
            eye.title = 'Show/hide in 3D view only (does not affect the calculation)';
            eye.addEventListener('click', (e) => { e.stopPropagation(); toggleVisible(vol.id); });

            row.appendChild(dot);
            row.appendChild(name);
            row.appendChild(badge);
            row.appendChild(calc);
            row.appendChild(eye);
            row.addEventListener('click', () => handleViewportPick(vol.id, null));
            list.appendChild(row);
        }
    }

    // -----------------------------------------------------------------------
    // Properties panel
    // -----------------------------------------------------------------------
    function fmtIn(cm) {
        const v = cm / IN;
        return (Math.round(v * 1000) / 1000).toString();
    }
    function fmtDeg(d) { return (Math.round(d * 100) / 100).toString(); }

    // Dimension form rows for a volume type (shared by the properties panel
    // and the Smart Dimension floating editor)
    function dimRowsHTML(vol, row, num) {
        const type = vol._type();
        if (type === 'annulus') {
            return row('Inner Radius', num('innerRadius', fmtIn(vol.innerRadius), 0.25), 'in')
                 + row('Outer Radius', num('outerRadius', fmtIn(vol.outerRadius), 0.25), 'in')
                 + row('Height', num('height', fmtIn(vol.height), 0.5), 'in');
        } else if (type === 'disk') {
            return row('Radius', num('radius', fmtIn(vol.radius), 0.25), 'in')
                 + row('Thickness', num('thickness', fmtIn(vol.thickness), 0.25), 'in');
        } else if (type === 'box') {
            return row('Width (X)', num('width', fmtIn(vol.width), 0.25), 'in')
                 + row('Height (Y)', num('height', fmtIn(vol.height), 0.25), 'in')
                 + row('Depth (Z)', num('depth', fmtIn(vol.depth), 0.25), 'in');
        } else if (type === 'sphere') {
            return row('Radius', num('radius', fmtIn(vol.radius), 0.25), 'in');
        }
        return row('Radius', num('radius', fmtIn(vol.radius), 0.25), 'in')
             + row('Height', num('height', fmtIn(vol.height), 0.5), 'in');
    }

    function renderProperties() {
        const panel = document.getElementById('propPanel');
        const body = document.getElementById('propBody');
        if (!panel || !body) return;

        const vol = selection ? model.getVolume(selection) : null;
        if (!vol) {
            panel.style.display = 'none';
            return;
        }
        panel.style.display = '';

        const matOpts = Materials.getMaterialList().map(m =>
            `<option value="${m.key}" ${vol.materialKey === m.key ? 'selected' : ''}>${m.name}</option>`
        ).join('');
        const isoOpts = Isotopes.getIsotopeList().map(i =>
            `<option value="${i.key}" ${vol.isotopeKey === i.key ? 'selected' : ''}>${i.key}</option>`
        ).join('');

        const row = (label, inner, unit) =>
            `<div class="form-row"><label>${label}</label>${inner}<span class="unit">${unit || ''}</span></div>`;
        const num = (field, val, step) =>
            `<input type="number" value="${val}" step="${step}" onchange="Editor.applyProp('${field}', this.value)">`;

        const dims = dimRowsHTML(vol, row, num);

        body.innerHTML =
            row('Name', `<input type="text" value="${(vol.label || '').replace(/"/g, '&quot;')}" onchange="Editor.applyProp('label', this.value)">`)
            + row('Role', `<select title="Source = emits radiation (gets isotope + activity). Shield / Container = attenuates only."
                onchange="Editor.applyProp('role', this.value)">
                <option value="shield" ${vol.role === 'shield' ? 'selected' : ''}>Shield</option>
                <option value="source" ${vol.role === 'source' ? 'selected' : ''}>Source</option>
                <option value="container" ${vol.role === 'container' ? 'selected' : ''}>Container</option>
              </select>`)
            + row('Material', `<select onchange="Editor.applyProp('materialKey', this.value)">${matOpts}</select>`)
            + row('In Calculation', `<input type="checkbox" style="flex:0" ${vol.enabled !== false ? 'checked' : ''}
                onchange="Editor.toggleEnabledSelected()">`)
            + (vol.role === 'source'
                ? row('Isotope', `<select onchange="Editor.applyProp('isotopeKey', this.value)">${isoOpts}</select>`)
                + row('Activity', num('activity_Ci', vol.activity_Ci || 0, 0.1), 'Ci')
                : '')
            + '<div class="divider"></div>'
            + row('X', num('posX', fmtIn(vol.position.x), 0.5), 'in')
            + row('Y (bottom)', num('posY', fmtIn(vol.position.y), 0.5), 'in')
            + row('Z', num('posZ', fmtIn(vol.position.z), 0.5), 'in')
            + row('Rot X', num('rotX', fmtDeg(vol.rotation.x), 15), 'deg')
            + row('Rot Y', num('rotY', fmtDeg(vol.rotation.y), 15), 'deg')
            + row('Rot Z', num('rotZ', fmtDeg(vol.rotation.z), 15), 'deg')
            + '<div class="divider"></div>'
            + dims
            + row('Priority', `<input type="number" value="${vol.priority}" step="5"
                title="When shapes overlap, the highest-priority shape decides the material at that point (e.g. a plug inside a lid opening needs higher priority than the lid)"
                onchange="Editor.applyProp('priority', this.value)">`,
                  'overlap')
            + `<div class="prop-actions">
                 <button onclick="Editor.duplicateSelected()">Duplicate</button>
                 <button class="danger" onclick="Editor.deleteSelected()">Delete</button>
               </div>`;
    }

    function applyProp(field, rawValue) {
        const vol = selection ? model.getVolume(selection) : null;
        if (!vol) return;
        pushUndo();

        const numVal = parseFloat(rawValue);
        switch (field) {
            case 'label': vol.label = rawValue; break;
            case 'role':
                vol.role = rawValue;
                if (rawValue === 'source') {
                    vol.isotopeKey = vol.isotopeKey || 'Co-60';
                    vol.activity_Ci = vol.activity_Ci || 1;
                }
                break;
            case 'materialKey': vol.materialKey = rawValue; break;
            case 'isotopeKey': vol.isotopeKey = rawValue; break;
            case 'activity_Ci': vol.activity_Ci = numVal || 0; break;
            case 'priority': vol.priority = Math.round(numVal) || 0; break;
            case 'posX': vol.position.x = numVal * IN; break;
            case 'posY': vol.position.y = numVal * IN; break;
            case 'posZ': vol.position.z = numVal * IN; break;
            case 'rotX': vol.setRotation({ ...vol.rotation, x: numVal }); break;
            case 'rotY': vol.setRotation({ ...vol.rotation, y: numVal }); break;
            case 'rotZ': vol.setRotation({ ...vol.rotation, z: numVal }); break;
            case 'radius': vol.radius = numVal * IN; break;
            case 'height': vol.height = numVal * IN; break;
            case 'thickness': vol.thickness = numVal * IN; vol.height = numVal * IN; break;
            case 'innerRadius': vol.innerRadius = numVal * IN; break;
            case 'outerRadius': vol.outerRadius = numVal * IN; break;
            case 'width': vol.width = numVal * IN; break;
            case 'depth': vol.depth = numVal * IN; break;
        }
        refreshAll(false);
    }

    function deleteSelected() { if (selection) deleteVolume(selection); }
    function duplicateSelected() { if (selection) duplicateVolume(selection); }

    // -----------------------------------------------------------------------
    // Smart Dimension floating editor: appears next to the clicked object,
    // edits its dimensions live (Enter/typing applies, Esc or X closes)
    // -----------------------------------------------------------------------
    let dimEl = null;

    function hideDimEditor() {
        if (dimEl) { dimEl.remove(); dimEl = null; }
    }

    function showDimEditor(id, screen) {
        hideDimEditor();
        const vol = model.getVolume(id);
        if (!vol) return;

        const row = (label, inner, unit) =>
            `<div class="form-row"><label>${label}</label>${inner}<span class="unit">${unit || ''}</span></div>`;
        const num = (field, val, step) =>
            `<input type="number" value="${val}" step="${step}" onchange="Editor.applyProp('${field}', this.value)">`;

        dimEl = document.createElement('div');
        dimEl.className = 'dim-editor';
        dimEl.innerHTML =
            `<div class="dim-editor-header">
                <span>${(displayName(vol) || '').replace(/</g, '&lt;')}</span>
                <button class="dim-editor-close" onclick="Editor.hideDimEditor()">&times;</button>
             </div>`
            + dimRowsHTML(vol, row, num);
        document.body.appendChild(dimEl);

        const mw = dimEl.offsetWidth, mh = dimEl.offsetHeight;
        dimEl.style.left = Math.min(screen.x + 14, window.innerWidth - mw - 8) + 'px';
        dimEl.style.top = Math.min(screen.y + 14, window.innerHeight - mh - 8) + 'px';
    }

    // -----------------------------------------------------------------------
    // Context menu
    // -----------------------------------------------------------------------
    function hideContextMenu() {
        if (ctxMenuEl) { ctxMenuEl.remove(); ctxMenuEl = null; }
    }

    function menuItem(text, fn, cls) {
        const item = document.createElement('div');
        item.className = 'ctx-item' + (cls ? ' ' + cls : '');
        item.textContent = text;
        item.addEventListener('click', () => { hideContextMenu(); fn(); });
        return item;
    }

    function menuHeader(text) {
        const h = document.createElement('div');
        h.className = 'ctx-header';
        h.textContent = text;
        return h;
    }

    function menuDivider() {
        const d = document.createElement('div');
        d.className = 'ctx-divider';
        return d;
    }

    function showContextMenu(id, screen, pt) {
        hideContextMenu();
        ctxMenuEl = document.createElement('div');
        ctxMenuEl.className = 'ctx-menu';

        if (id) {
            const vol = model.getVolume(id);
            // Keep the current selection when right-clicking a DIFFERENT
            // volume: that enables the "align selected to this" workflow.
            const alignSource = (selection && selection !== id)
                ? model.getVolume(selection) : null;
            if (!alignSource) select(id);
            ctxMenuEl.appendChild(menuHeader(displayName(vol)));
            ctxMenuEl.appendChild(menuItem('Duplicate  (Ctrl+D)', () => duplicateVolume(id)));
            ctxMenuEl.appendChild(menuItem('Delete  (Del)', () => deleteVolume(id), 'danger'));
            ctxMenuEl.appendChild(menuItem(
                vol.enabled === false ? 'Include in calculation' : 'Exclude from calculation',
                () => toggleEnabled(id)));
            ctxMenuEl.appendChild(menuDivider());
            if (vol.role !== 'source') {
                ctxMenuEl.appendChild(menuItem('Make Source (radioactive)', () => setRole(id, 'source')));
            }
            if (vol.role !== 'shield') {
                ctxMenuEl.appendChild(menuItem('Make Shield', () => setRole(id, 'shield')));
            }
            ctxMenuEl.appendChild(menuDivider());
            ctxMenuEl.appendChild(menuHeader('Material'));
            for (const m of Materials.getMaterialList()) {
                ctxMenuEl.appendChild(menuItem(
                    (vol.materialKey === m.key ? '✓ ' : ' ') + m.name,
                    () => setMaterial(id, m.key)));
            }
            if (alignSource) {
                ctxMenuEl.appendChild(menuDivider());
                ctxMenuEl.appendChild(menuHeader(
                    'Align "' + displayName(alignSource) + '" to this'));
                for (const m of ALIGN_MODES) {
                    ctxMenuEl.appendChild(menuItem(m.label,
                        () => alignVolumes(alignSource.id, id, m.key)));
                }
            }
        } else {
            ctxMenuEl.appendChild(menuHeader('Add at this point'));
            ctxMenuEl.appendChild(menuItem('+ Box / cube (shield)', () => addVolume('box', 'shield', pt)));
            ctxMenuEl.appendChild(menuItem('+ Plate / wall (shield)', () => addVolume('plate', 'shield', pt)));
            ctxMenuEl.appendChild(menuItem('+ Cylinder (shield)', () => addVolume('cylinder', 'shield', pt)));
            ctxMenuEl.appendChild(menuItem('+ Disk (shield)', () => addVolume('disk', 'shield', pt)));
            ctxMenuEl.appendChild(menuItem('+ Annulus / pipe (shield)', () => addVolume('annulus', 'shield', pt)));
            ctxMenuEl.appendChild(menuItem('+ Sphere (shield)', () => addVolume('sphere', 'shield', pt)));
            ctxMenuEl.appendChild(menuItem('+ Source cylinder', () => addVolume('cylinder', 'source', pt)));
            ctxMenuEl.appendChild(menuItem('+ Source sphere', () => addVolume('sphere', 'source', pt)));
            ctxMenuEl.appendChild(menuDivider());
            if (pt) {
                ctxMenuEl.appendChild(menuItem('Place dose point here', () => placeDosePoint(pt)));
            }
        }

        document.body.appendChild(ctxMenuEl);
        // Keep the menu on-screen
        const mw = ctxMenuEl.offsetWidth, mh = ctxMenuEl.offsetHeight;
        ctxMenuEl.style.left = Math.min(screen.x, window.innerWidth - mw - 8) + 'px';
        ctxMenuEl.style.top = Math.min(screen.y, window.innerHeight - mh - 8) + 'px';
    }

    // -----------------------------------------------------------------------
    // Pipe / Hose builder
    // A run of straight legs from a start point. Each leg becomes a rotated
    // content cylinder (+ wall annulus if wall > 0). After the first leg,
    // each leg is extended backward by the outer radius so corners have no
    // void at the bend. Total activity is split across legs by volume.
    // -----------------------------------------------------------------------
    const PIPE_DIRS = {
        '+Y': { v: [0, 1, 0],  rot: { x: 0,    y: 0, z: 0 },   label: 'Up (+Y)' },
        '-Y': { v: [0, -1, 0], rot: { x: 180,  y: 0, z: 0 },   label: 'Down (-Y)' },
        '+X': { v: [1, 0, 0],  rot: { x: 0,    y: 0, z: -90 }, label: '+X (east)' },
        '-X': { v: [-1, 0, 0], rot: { x: 0,    y: 0, z: 90 },  label: '-X (west)' },
        '+Z': { v: [0, 0, 1],  rot: { x: 90,   y: 0, z: 0 },   label: '+Z (south)' },
        '-Z': { v: [0, 0, -1], rot: { x: -90,  y: 0, z: 0 },   label: '-Z (north)' }
    };

    function buildPipe(cfg) {
        const legs = (cfg.legs || []).filter(l => PIPE_DIRS[l.dir] && l.length > 0);
        if (!legs.length) { status('Pipe needs at least one leg'); return; }

        const outerR = cfg.outerR;
        const wall = Math.max(0, Math.min(cfg.wall || 0, outerR * 0.95));
        const contentR = outerR - wall;
        const name = cfg.name || 'Pipe';

        pushUndo();

        // Effective geometry per leg (with corner back-extension)
        const built = [];
        let cursor = { ...cfg.start };
        legs.forEach((leg, i) => {
            const d = PIPE_DIRS[leg.dir];
            const ext = i > 0 ? outerR : 0;
            const pos = {
                x: cursor.x - d.v[0] * ext,
                y: cursor.y - d.v[1] * ext,
                z: cursor.z - d.v[2] * ext
            };
            built.push({ pos, rot: d.rot, len: leg.length + ext });
            cursor = {
                x: cursor.x + d.v[0] * leg.length,
                y: cursor.y + d.v[1] * leg.length,
                z: cursor.z + d.v[2] * leg.length
            };
        });

        const totalContentVol = built.reduce(
            (s, b) => s + Math.PI * contentR * contentR * b.len, 0);

        built.forEach((b, i) => {
            const contentCfg = {
                role: cfg.source ? 'source' : 'shield',
                materialKey: cfg.contentsMaterial || 'water',
                position: b.pos,
                rotation: b.rot,
                priority: 30,
                label: name + ' leg ' + (i + 1),
                dimensions: { radius: contentR, height: b.len }
            };
            if (cfg.source) {
                contentCfg.isotopeKey = cfg.source.isotopeKey || 'Co-60';
                contentCfg.activity_Ci = (cfg.source.activity_Ci || 0) *
                    (Math.PI * contentR * contentR * b.len) / totalContentVol;
            }
            model.addVolume(new Geometry.CylinderVolume(contentCfg));

            if (wall > 0) {
                model.addVolume(new Geometry.AnnulusVolume({
                    role: 'shield',
                    materialKey: cfg.wallMaterial || 'steel',
                    position: { ...b.pos },
                    rotation: { ...b.rot },
                    priority: 60,
                    label: name + ' wall ' + (i + 1),
                    dimensions: { innerRadius: contentR, outerRadius: outerR, height: b.len }
                }));
            }
        });

        refreshAll(false);
        status('Built ' + name + ': ' + legs.length + ' leg(s), ends at (' +
            (cursor.x / IN).toFixed(1) + '", ' + (cursor.y / IN).toFixed(1) + '", ' +
            (cursor.z / IN).toFixed(1) + '")');
        return cursor;
    }

    // --- Pipe builder dialog ---
    let pipeLegs = [];

    function showPipeBuilder() {
        pipeLegs = [{ dir: '+Y', length: 300 }, { dir: '-X', length: 240 }];

        // Populate material/isotope selects once
        const matOpts = Materials.getMaterialList().map(m =>
            `<option value="${m.key}">${m.name}</option>`).join('');
        const wallSel = document.getElementById('pipeWallMat');
        const contSel = document.getElementById('pipeContentsMat');
        if (!wallSel.options.length) {
            wallSel.innerHTML = matOpts; wallSel.value = 'steel';
            contSel.innerHTML = matOpts; contSel.value = 'water';
            document.getElementById('pipeIsotope').innerHTML =
                Isotopes.getIsotopeList().map(i => `<option value="${i.key}">${i.key}</option>`).join('');
        }

        renderPipeLegs();
        document.getElementById('pipeModal').style.display = 'flex';
    }

    function hidePipeBuilder() {
        document.getElementById('pipeModal').style.display = 'none';
    }

    function addPipeLeg() {
        pipeLegs.push({ dir: '+Y', length: 60 });
        renderPipeLegs();
    }

    function removePipeLeg(i) {
        pipeLegs.splice(i, 1);
        renderPipeLegs();
    }

    function renderPipeLegs() {
        const list = document.getElementById('pipeLegList');
        if (!list) return;
        list.innerHTML = '';
        pipeLegs.forEach((leg, i) => {
            const div = document.createElement('div');
            div.className = 'layer-item';
            const dirOpts = Object.entries(PIPE_DIRS).map(([k, d]) =>
                `<option value="${k}" ${leg.dir === k ? 'selected' : ''}>${d.label}</option>`).join('');
            div.innerHTML =
                `<span style="color:#8b949e; min-width:16px;">${i + 1}.</span>` +
                `<select style="width:110px" onchange="Editor._setPipeLeg(${i},'dir',this.value)">${dirOpts}</select>` +
                `<input type="number" value="${leg.length}" step="1" min="0.1"
                     onchange="Editor._setPipeLeg(${i},'length',parseFloat(this.value))">` +
                `<span class="unit">in</span>` +
                `<button class="remove-btn" onclick="Editor._removePipeLeg(${i})">&times;</button>`;
            list.appendChild(div);
        });
    }

    function _setPipeLeg(i, field, value) {
        if (pipeLegs[i]) pipeLegs[i][field] = value;
    }

    function pipeStartAtSelectedTop() {
        const vol = selection ? model.getVolume(selection) : null;
        if (!vol) { status('Select a volume first (its top-center becomes the start)'); return; }
        const top = vol.localToWorld(0, volHeight(vol), 0);
        document.getElementById('pipeStartX').value = (top.x / IN).toFixed(2);
        document.getElementById('pipeStartY').value = (top.y / IN).toFixed(2);
        document.getElementById('pipeStartZ').value = (top.z / IN).toFixed(2);
        status('Pipe start set to top-center of ' + displayName(vol));
    }

    function buildPipeFromDialog() {
        const val = id => parseFloat(document.getElementById(id).value) || 0;
        const cfg = {
            name: document.getElementById('pipeName').value || 'Pipe',
            start: { x: val('pipeStartX') * IN, y: val('pipeStartY') * IN, z: val('pipeStartZ') * IN },
            outerR: val('pipeOuterR') * IN,
            wall: val('pipeWall') * IN,
            wallMaterial: document.getElementById('pipeWallMat').value,
            contentsMaterial: document.getElementById('pipeContentsMat').value,
            legs: pipeLegs.map(l => ({ dir: l.dir, length: l.length * IN })),
            source: document.getElementById('pipeIsSource').checked
                ? {
                    isotopeKey: document.getElementById('pipeIsotope').value,
                    activity_Ci: val('pipeActivity')
                  }
                : null
        };
        if (cfg.outerR <= 0) { status('Pipe outer radius must be > 0'); return; }
        hidePipeBuilder();
        buildPipe(cfg);
    }

    // -----------------------------------------------------------------------
    // Public API
    // -----------------------------------------------------------------------
    return {
        init,
        getModel: () => model,
        getSelection: () => selection,
        select,
        setMode,
        undo,
        redo,
        addVolume,
        deleteSelected,
        duplicateSelected,
        applyProp,
        toggleEnabledSelected: () => { if (selection) toggleEnabled(selection); },
        startMate,
        hideDimEditor,
        applyTankTemplate,
        newScene,
        saveToFile,
        loadFromFile,
        refreshAll,
        alignVolumes,
        buildPipe,
        showPipeBuilder,
        hidePipeBuilder,
        addPipeLeg,
        pipeStartAtSelectedTop,
        buildPipeFromDialog,
        _setPipeLeg,
        _removePipeLeg: removePipeLeg
    };

})();
